use arkade_bindgen::{generate_from_str, Options, Target};

fn load_fixture(name: &str) -> String {
    let path = format!(
        "{}/tests/fixtures/{}.json",
        env!("CARGO_MANIFEST_DIR"),
        name
    );
    std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("Failed to load fixture '{}': {}", path, e))
}

fn gen(name: &str, opts: &Options) -> String {
    generate_from_str(&load_fixture(name), Target::Go, opts)
        .expect("codegen should succeed")
        .content
}

#[test]
fn test_htlc_go_generates() {
    let generated =
        generate_from_str(&load_fixture("htlc"), Target::Go, &Options::default()).expect("codegen");
    assert_eq!(generated.filename, "htlc.go");
    let code = &generated.content;

    // Header + imports
    assert!(code.contains("Code generated by arkade-bindgen"));
    assert!(code.contains("DO NOT EDIT"));
    assert!(code.contains("package contracts"));
    assert!(code.contains("\"github.com/arkade-os/contract-sdk-go/ark\""));
    assert!(code.contains("_ \"embed\""));

    // Constructor params struct
    assert!(code.contains("type HTLCParams struct {"));
    assert!(code.contains("Sender [33]byte"));
    assert!(code.contains("Receiver [33]byte"));
    assert!(code.contains("PreimageHash [20]byte"));
    assert!(code.contains("RefundTime int64"));

    // Per-leaf witness structs (name collapses when leaf == group)
    assert!(code.contains("type HTLCClaimWitness struct {"));
    assert!(code.contains("Preimage []byte"));
    assert!(code.contains("// ServerSig injected by Arkade"));
    assert!(code.contains("// EmulatorSig injected by Arkade"));
    assert!(code.contains("type HTLCUnilateralWitness struct {"));
    assert!(code.contains("SenderSig [64]byte"));

    // Contract struct + constructor
    assert!(code.contains("type HTLC struct {"));
    assert!(code.contains("*ark.Contract"));
    assert!(code.contains("func NewHTLC(params HTLCParams) (*HTLC, error)"));
    assert!(code.contains("ark.NewContract(htlcArtifact"));
    assert!(code.contains("params.Sender[:]"));
    assert!(code.contains("Encoding: ark.Compressed33"));
    assert!(code.contains("ark.EncodeScriptNum(params.RefundTime)"));

    // Per-leaf methods calling BuildWitness(group, leaf, ...)
    assert!(code.contains("func (h *HTLC) Claim(w HTLCClaimWitness) (*ark.WitnessStack, error)"));
    assert!(code.contains("h.BuildWitness(\"claim\", \"claim\""));
    assert!(code.contains("func (h *HTLC) Unilateral(w HTLCUnilateralWitness)"));
    assert!(code.contains("h.BuildWitness(\"unilateral\", \"unilateral\""));
    assert!(code.contains("w.SenderSig[:]"));
    assert!(code.contains("Encoding: ark.Schnorr64"));
}

#[test]
fn test_single_sig_go() {
    let generated = generate_from_str(&load_fixture("single_sig"), Target::Go, &Options::default())
        .expect("codegen");
    assert_eq!(generated.filename, "single_sig.go");

    let code = &generated.content;
    assert!(code.contains("type SingleSigParams struct {"));
    assert!(code.contains("User [33]byte"));
    assert!(code.contains("func NewSingleSig(params SingleSigParams)"));
    assert!(code.contains("func (s *SingleSig) Spend(w SingleSigSpendWitness)"));
    assert!(code.contains("func (s *SingleSig) Unilateral(w SingleSigUnilateralWitness)"));
}

#[test]
fn test_go_custom_package() {
    let opts = Options {
        embed: false,
        package: Some("mypackage".to_string()),
    };
    assert!(gen("single_sig", &opts).contains("package mypackage"));
}

#[test]
fn test_go_embed_mode() {
    let opts = Options {
        embed: true,
        package: None,
    };
    let code = gen("single_sig", &opts);
    assert!(code.contains("var singleSigArtifact = []byte(\""));
    assert!(!code.contains("//go:embed"));
    assert!(!code.contains("_ \"embed\""));
}

#[test]
fn test_go_fixed_array_types() {
    let code = gen("htlc", &Options::default());
    assert!(code.contains("[33]byte")); // pubkey
    assert!(code.contains("[64]byte")); // signature
    assert!(code.contains("PreimageHash [20]byte")); // bytes20
    assert!(code.contains("RefundTime int64")); // int
}

#[test]
fn test_go_dotted_fields_remain_distinct() {
    let artifact = arkade_compiler::compile(
        r#"
struct Inner { int b; }
struct Ambiguous { int a_b; Inner a; }
contract C(Ambiguous value) {
    function spend() { require(true); }
}
"#,
    )
    .unwrap();
    let json = serde_json::to_string(&artifact).unwrap();
    let code = generate_from_str(&json, Target::Go, &Options::default())
        .unwrap()
        .content;

    assert!(code.contains("Value_Da_Ub int64"));
    assert!(code.contains("Value_Da_Db int64"));
    assert!(code.contains("Name: \"value.a_b\""));
    assert!(code.contains("Name: \"value.a.b\""));
}
