use arkade_bindgen::{generate_from_str, Options, Target};

fn load_fixture(name: &str) -> String {
    let path = format!(
        "{}/tests/fixtures/{}.json",
        env!("CARGO_MANIFEST_DIR"),
        name
    );
    std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("Failed to load fixture '{}': {}", path, e))
}

#[test]
fn test_htlc_go_generates() {
    let json = load_fixture("htlc");
    let result = generate_from_str(&json, Target::Go, &Options::default());
    let generated = result.expect("codegen should succeed");

    assert_eq!(generated.filename, "htlc.go");

    let code = &generated.content;

    // Header
    assert!(code.contains("Code generated by arkade-bindgen"));
    assert!(code.contains("DO NOT EDIT"));
    assert!(code.contains("package contracts"));

    // Imports (includes embed for non-embed mode)
    assert!(code.contains("\"github.com/arkade-os/contract-sdk-go/ark\""));
    assert!(code.contains("_ \"embed\""));

    // Constructor params struct
    assert!(code.contains("type HTLCParams struct {"));
    assert!(code.contains("Sender [33]byte"));
    assert!(code.contains("Receiver [33]byte"));
    assert!(code.contains("Hash []byte"));
    assert!(code.contains("RefundTime int64"));

    // Claim witness structs
    assert!(code.contains("type HTLCClaimCooperativeWitness struct {"));
    assert!(code.contains("ReceiverSig [64]byte"));
    assert!(code.contains("Preimage []byte"));
    assert!(code.contains("// ServerSig injected by Ark server"));

    assert!(code.contains("type HTLCClaimExitWitness struct {"));
    assert!(code.contains("// Exit timelock enforced by script"));

    // Contract struct
    assert!(code.contains("type HTLC struct {"));
    assert!(code.contains("*ark.Contract"));

    // Constructor function
    assert!(code.contains("func NewHTLC(params HTLCParams) (*HTLC, error)"));
    assert!(code.contains("ark.NewContract(htlcArtifact"));
    assert!(code.contains("params.Sender[:]"));
    assert!(code.contains("Encoding: ark.Compressed33"));
    assert!(code.contains("ark.EncodeScriptNum(params.RefundTime)"));

    // Methods
    assert!(code.contains("func (h *HTLC) ClaimCooperative(w HTLCClaimCooperativeWitness)"));
    assert!(code.contains("(*ark.WitnessStack, error)"));
    assert!(code.contains("h.BuildWitness(\"claim\", true"));
    assert!(code.contains("w.ReceiverSig[:]"));
    assert!(code.contains("Encoding: ark.Schnorr64"));

    assert!(code.contains("func (h *HTLC) ClaimExit(w HTLCClaimExitWitness)"));
    assert!(code.contains("h.BuildWitness(\"claim\", false"));
}

#[test]
fn test_single_sig_go() {
    let json = load_fixture("single_sig");
    let result = generate_from_str(&json, Target::Go, &Options::default());
    let generated = result.expect("codegen should succeed");

    assert_eq!(generated.filename, "single_sig.go");

    let code = &generated.content;
    assert!(code.contains("type SingleSigParams struct {"));
    assert!(code.contains("OwnerPk [33]byte"));
    assert!(code.contains("func NewSingleSig(params SingleSigParams)"));
    assert!(code.contains("func (s *SingleSig) SpendCooperative"));
    assert!(code.contains("func (s *SingleSig) SpendExit"));
}

#[test]
fn test_go_custom_package() {
    let json = load_fixture("single_sig");
    let opts = Options {
        embed: false,
        package: Some("mypackage".to_string()),
    };
    let result = generate_from_str(&json, Target::Go, &opts);
    let code = result.unwrap().content;
    assert!(code.contains("package mypackage"));
}

#[test]
fn test_go_embed_mode() {
    let json = load_fixture("single_sig");
    let opts = Options {
        embed: true,
        package: None,
    };
    let result = generate_from_str(&json, Target::Go, &opts);
    let code = result.unwrap().content;

    // Should have inline artifact (uses interpreted string literal, not raw backtick)
    assert!(code.contains("var singleSigArtifact = []byte(\""));
    assert!(!code.contains("//go:embed"));
    // Embed mode should not import embed package
    assert!(!code.contains("_ \"embed\""));
}

#[test]
fn test_go_fixed_array_types() {
    let json = load_fixture("htlc");
    let result = generate_from_str(&json, Target::Go, &Options::default());
    let code = result.unwrap().content;

    // pubkey → [33]byte
    assert!(code.contains("[33]byte"));
    // signature → [64]byte
    assert!(code.contains("[64]byte"));
    // bytes → []byte
    assert!(code.contains("Hash []byte"));
    // int → int64
    assert!(code.contains("RefundTime int64"));
}

#[test]
fn test_legacy_artifact_go() {
    let json = load_fixture("htlc_legacy");
    let result = generate_from_str(&json, Target::Go, &Options::default());
    let generated = result.expect("legacy artifact should still generate");

    let code = &generated.content;
    assert!(code.contains("type HTLCClaimCooperativeWitness struct {"));
    assert!(code.contains("ReceiverSig [64]byte"));
}
