use arkade_bindgen::{generate_from_str, Options, Target};

fn load_fixture(name: &str) -> String {
    let path = format!(
        "{}/tests/fixtures/{}.json",
        env!("CARGO_MANIFEST_DIR"),
        name
    );
    std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("Failed to load fixture '{}': {}", path, e))
}

#[test]
fn test_htlc_typescript_generates() {
    let json = load_fixture("htlc");
    let result = generate_from_str(&json, Target::TypeScript, &Options::default());
    let generated = result.expect("codegen should succeed");

    assert_eq!(generated.filename, "htlc.ts");

    let code = &generated.content;

    // Header
    assert!(code.contains("Auto-generated by arkade-bindgen"));
    assert!(code.contains("Source contract: HTLC"));

    // Imports
    assert!(code.contains("from \"@arkade-os/contract-sdk\""));
    assert!(code.contains("ArkContract"));
    assert!(code.contains("type Signature"));
    assert!(code.contains("type Bytes"));
    assert!(code.contains("type Pubkey"));

    // Constructor params interface
    assert!(code.contains("export interface HTLCParams {"));
    assert!(code.contains("sender: Pubkey;"));
    assert!(code.contains("receiver: Pubkey;"));
    assert!(code.contains("hash: Bytes;"));
    assert!(code.contains("refundTime: bigint;"));

    // Claim witness interfaces
    assert!(code.contains("export interface HTLCClaimCooperativeWitness {"));
    assert!(code.contains("receiverSig: Signature;"));
    assert!(code.contains("preimage: Bytes;"));
    assert!(code.contains("// serverSig injected by Ark server"));

    assert!(code.contains("export interface HTLCClaimExitWitness {"));
    assert!(code.contains("// exit timelock enforced by script"));

    // Class
    assert!(code.contains("export class HTLC extends ArkContract<HTLCParams>"));
    assert!(code.contains("static readonly artifact = artifact"));

    // Function methods — object grouping pattern
    assert!(code.contains("claim = {"));
    assert!(code.contains("cooperative: (witness: HTLCClaimCooperativeWitness)"));
    assert!(code.contains("this.buildWitness(\"claim\", true, witness)"));
    assert!(code.contains("exit: (witness: HTLCClaimExitWitness)"));
    assert!(code.contains("this.buildWitness(\"claim\", false, witness)"));

    // Together and refund methods also exist
    assert!(code.contains("together = {"));
    assert!(code.contains("refund = {"));
}

#[test]
fn test_single_sig_typescript() {
    let json = load_fixture("single_sig");
    let result = generate_from_str(&json, Target::TypeScript, &Options::default());
    let generated = result.expect("codegen should succeed");

    assert_eq!(generated.filename, "single_sig.ts");

    let code = &generated.content;
    assert!(code.contains("export interface SingleSigParams {"));
    assert!(code.contains("ownerPk: Pubkey;"));
    assert!(code.contains("export class SingleSig extends ArkContract<SingleSigParams>"));
    assert!(code.contains("spend = {"));
}

#[test]
fn test_legacy_artifact_without_witness_schema() {
    let json = load_fixture("htlc_legacy");
    let result = generate_from_str(&json, Target::TypeScript, &Options::default());
    let generated = result.expect("legacy artifact should still generate");

    let code = &generated.content;
    // Should still produce witness interfaces with inferred types
    assert!(code.contains("export interface HTLCClaimCooperativeWitness {"));
    assert!(code.contains("receiverSig: Signature;"));
    assert!(code.contains("preimage: Bytes;"));
}

#[test]
fn test_typescript_embed_mode() {
    let json = load_fixture("single_sig");
    let opts = Options {
        embed: true,
        package: None,
    };
    let result = generate_from_str(&json, Target::TypeScript, &opts);
    let generated = result.expect("codegen should succeed");

    let code = &generated.content;
    // Should have inline artifact instead of import
    assert!(code.contains("const artifact ="));
    assert!(!code.contains("import artifact from"));
}

#[test]
fn test_typescript_function_order_preserved() {
    let json = load_fixture("htlc");
    let result = generate_from_str(&json, Target::TypeScript, &Options::default());
    let code = result.unwrap().content;

    // together should appear before refund, which should appear before claim
    let together_pos = code.find("together = {").unwrap();
    let refund_pos = code.find("refund = {").unwrap();
    let claim_pos = code.find("claim = {").unwrap();
    assert!(together_pos < refund_pos);
    assert!(refund_pos < claim_pos);
}
