use arkade_bindgen::{generate_from_str, Options, Target};

fn load_fixture(name: &str) -> String {
    let path = format!(
        "{}/tests/fixtures/{}.json",
        env!("CARGO_MANIFEST_DIR"),
        name
    );
    std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("Failed to load fixture '{}': {}", path, e))
}

fn gen(name: &str) -> String {
    let json = load_fixture(name);
    generate_from_str(&json, Target::TypeScript, &Options::default())
        .expect("codegen should succeed")
        .content
}

#[test]
fn test_htlc_typescript_generates() {
    let json = load_fixture("htlc");
    let generated =
        generate_from_str(&json, Target::TypeScript, &Options::default()).expect("codegen");
    assert_eq!(generated.filename, "htlc.ts");
    let code = &generated.content;

    // Header
    assert!(code.contains("Auto-generated by arkade-bindgen"));
    assert!(code.contains("Source contract: HTLC"));

    // Imports
    assert!(code.contains("from \"@arkade-os/contract-sdk\""));
    assert!(code.contains("ArkContract"));
    assert!(code.contains("type Signature"));
    assert!(code.contains("type Bytes"));
    assert!(code.contains("type Pubkey"));

    // Constructor params interface
    assert!(code.contains("export interface HTLCParams {"));
    assert!(code.contains("sender: Pubkey;"));
    assert!(code.contains("receiver: Pubkey;"));
    assert!(code.contains("preimageHash: Bytes20;"));
    assert!(code.contains("refundTime: bigint;"));

    // Per-leaf witness interfaces (name collapses when leaf == group)
    assert!(code.contains("export interface HTLCClaimWitness {"));
    assert!(code.contains("preimage: Bytes;"));
    assert!(code.contains("// serverSig injected by Arkade"));
    assert!(code.contains("// emulatorSig injected by Arkade"));
    assert!(code.contains("export interface HTLCUnilateralWitness {"));
    assert!(code.contains("senderSig: Signature;"));

    // Class
    assert!(code.contains("export class HTLC extends ArkContract<HTLCParams>"));
    assert!(code.contains("static readonly artifact = artifact"));

    // Per-group method objects keyed by leaf, calling buildWitness(group, leaf, w)
    assert!(code.contains("claim = {"));
    assert!(code.contains("claim: (witness: HTLCClaimWitness) =>"));
    assert!(code.contains("this.buildWitness(\"claim\", \"claim\", witness)"));
    assert!(code.contains("unilateral = {"));
    assert!(code.contains("this.buildWitness(\"unilateral\", \"unilateral\", witness)"));
}

#[test]
fn test_single_sig_typescript() {
    let generated = generate_from_str(
        &load_fixture("single_sig"),
        Target::TypeScript,
        &Options::default(),
    )
    .expect("codegen");
    assert_eq!(generated.filename, "single_sig.ts");

    let code = &generated.content;
    assert!(code.contains("export interface SingleSigParams {"));
    assert!(code.contains("user: Pubkey;"));
    assert!(code.contains("export class SingleSig extends ArkContract<SingleSigParams>"));
    assert!(code.contains("spend = {"));
    assert!(code.contains("unilateral = {"));
}

#[test]
fn test_typescript_embed_mode() {
    let opts = Options {
        embed: true,
        package: None,
    };
    let code = generate_from_str(&load_fixture("single_sig"), Target::TypeScript, &opts)
        .expect("codegen")
        .content;
    assert!(code.contains("const artifact ="));
    assert!(!code.contains("import artifact from"));
}

#[test]
fn test_typescript_group_order_preserved() {
    let code = gen("htlc");
    let claim = code.find("claim = {").unwrap();
    let refund = code.find("refund = {").unwrap();
    let uni = code.find("unilateral = {").unwrap();
    assert!(claim < refund);
    assert!(refund < uni);
}
