use crate::ir::{ContractIR, Encoding, Field, GroupIR, LeafIR};
use crate::naming::{to_camel_case, to_pascal_case, to_snake_case};
use crate::targets::{CodegenOptions, CodegenTarget, GeneratedFile};

pub struct GoTarget;

impl CodegenTarget for GoTarget {
    fn name(&self) -> &str {
        "go"
    }

    fn file_extension(&self) -> &str {
        "go"
    }

    fn generate(&self, ir: &ContractIR, options: &CodegenOptions) -> Result<GeneratedFile, String> {
        let filename = format!("{}.go", to_snake_case(&ir.name));
        let content = generate_go(ir, options);
        Ok(GeneratedFile { filename, content })
    }
}

fn go_type_for_field(field: &Field) -> &'static str {
    match field.encoding {
        Encoding::Compressed33 => "[33]byte",
        Encoding::Schnorr64 => "[64]byte",
        Encoding::Raw => "[]byte",
        Encoding::Raw20 => "[20]byte",
        Encoding::Raw32 => "[32]byte",
        Encoding::ScriptNum => {
            if field.ark_type == "bool" {
                "bool"
            } else {
                "int64"
            }
        }
        Encoding::Le64 => "uint64",
        Encoding::Le32 => "uint32",
        Encoding::Unknown(_) => "[]byte",
    }
}

/// Whether this encoding uses a fixed-size array (needs [:] for slice conversion).
fn is_fixed_array(encoding: &Encoding) -> bool {
    matches!(
        encoding,
        Encoding::Compressed33 | Encoding::Schnorr64 | Encoding::Raw20 | Encoding::Raw32
    )
}

/// Map encoding to the ark SDK constant name.
fn encoding_const(encoding: &Encoding) -> &'static str {
    match encoding {
        Encoding::Compressed33 => "ark.Compressed33",
        Encoding::Schnorr64 => "ark.Schnorr64",
        Encoding::Raw => "ark.Raw",
        Encoding::Raw20 => "ark.Raw20",
        Encoding::Raw32 => "ark.Raw32",
        Encoding::ScriptNum => "ark.ScriptNum",
        Encoding::Le64 => "ark.Le64",
        Encoding::Le32 => "ark.Le32",
        Encoding::Unknown(_) => "ark.Raw",
    }
}

/// How to convert a Go typed field value to []byte for the witness builder.
fn value_expr(field: &Field, prefix: &str) -> String {
    let go_name = to_pascal_case(&field.name);
    match field.encoding {
        Encoding::ScriptNum => {
            if field.ark_type == "bool" {
                format!("ark.EncodeBool({}.{})", prefix, go_name)
            } else {
                format!("ark.EncodeScriptNum({}.{})", prefix, go_name)
            }
        }
        Encoding::Le64 => format!("ark.EncodeLe64({}.{})", prefix, go_name),
        Encoding::Le32 => format!("ark.EncodeLe32({}.{})", prefix, go_name),
        _ if is_fixed_array(&field.encoding) => format!("{}.{}[:]", prefix, go_name),
        _ => format!("{}.{}", prefix, go_name),
    }
}

/// PascalCase name suffix identifying a leaf. Collapses the redundant part when a
/// group has a single leaf sharing its name (e.g. `Claim`, not `ClaimClaim`).
fn leaf_suffix(group: &GroupIR, leaf: &LeafIR) -> String {
    if leaf.name == group.name {
        to_pascal_case(&group.name)
    } else {
        format!(
            "{}{}",
            to_pascal_case(&group.name),
            to_pascal_case(&leaf.name)
        )
    }
}

fn witness_struct_name(ir: &ContractIR, group: &GroupIR, leaf: &LeafIR) -> String {
    format!("{}{}Witness", ir.name, leaf_suffix(group, leaf))
}

fn generate_go(ir: &ContractIR, options: &CodegenOptions) -> String {
    let mut out = String::new();

    let version = ir.compiler_version.as_deref().unwrap_or("unknown");
    let package = options.package_name.as_deref().unwrap_or("contracts");

    // Header
    let embed_import = if options.embed_artifact {
        ""
    } else {
        "\n\t_ \"embed\""
    };
    out.push_str(&format!(
        "// Code generated by arkade-bindgen v0.1.0. DO NOT EDIT.\n\
         // Source contract: {}\n\
         // Compiler: arkade-compiler v{}\n\n\
         package {}\n\n\
         import ({embed}\n\t\"github.com/arkade-os/contract-sdk-go/ark\"\n)\n\n",
        ir.name,
        version,
        package,
        embed = embed_import,
    ));

    // Constructor params struct
    out.push_str(&format!(
        "// {}Params holds constructor parameters for the {} contract.\n",
        ir.name, ir.name
    ));
    out.push_str(&format!("type {}Params struct {{\n", ir.name));
    for field in &ir.constructor_fields {
        out.push_str(&format!(
            "\t{} {} // {} ({})\n",
            to_pascal_case(&field.name),
            go_type_for_field(field),
            field.ark_type,
            field.encoding.as_str(),
        ));
    }
    out.push_str("}\n\n");

    // Per-leaf witness structs
    for group in &ir.groups {
        for leaf in &group.leaves {
            emit_witness_struct(&mut out, ir, group, leaf);
        }
    }

    // Contract struct
    out.push_str(&format!(
        "// {} wraps an Arkade contract instance.\n",
        ir.name
    ));
    out.push_str(&format!(
        "type {} struct {{\n\t*ark.Contract\n}}\n\n",
        ir.name
    ));

    // Constructor function
    let camel_name = to_camel_case(&ir.name);
    out.push_str(&format!(
        "// New{} creates a new {} contract instance.\n",
        ir.name, ir.name
    ));
    out.push_str(&format!(
        "func New{}(params {}Params) (*{}, error) {{\n",
        ir.name, ir.name, ir.name,
    ));
    out.push_str(&format!(
        "\tc, err := ark.NewContract({}Artifact, ark.ConstructorArgs{{\n",
        camel_name,
    ));
    for field in &ir.constructor_fields {
        out.push_str(&format!(
            "\t\t{{Name: \"{}\", Value: {}, Encoding: {}}},\n",
            field.name,
            value_expr(field, "params"),
            encoding_const(&field.encoding),
        ));
    }
    out.push_str("\t})\n");
    out.push_str("\tif err != nil {\n\t\treturn nil, err\n\t}\n");
    out.push_str(&format!(
        "\treturn &{}{{Contract: c}}, nil\n}}\n\n",
        ir.name
    ));

    // Per-leaf spend methods
    let receiver = pick_receiver(&ir.name);
    for group in &ir.groups {
        for leaf in &group.leaves {
            emit_go_method(&mut out, ir, group, leaf, &receiver);
        }
    }

    // Artifact constant
    if options.embed_artifact {
        if let Some(ref json) = options.artifact_json {
            let escaped = escape_go_string(json.trim());
            out.push_str(&format!(
                "var {}Artifact = []byte(\"{}\")\n",
                camel_name, escaped,
            ));
        }
    } else {
        let snake_name = to_snake_case(&ir.name);
        out.push_str(&format!(
            "//go:embed {}.json\nvar {}Artifact []byte\n",
            snake_name, camel_name,
        ));
    }

    out
}

fn emit_witness_struct(out: &mut String, ir: &ContractIR, group: &GroupIR, leaf: &LeafIR) {
    let struct_name = witness_struct_name(ir, group, leaf);

    out.push_str(&format!(
        "// {} holds witness data for {}.{} (leaf: {}).\n",
        struct_name, ir.name, group.name, leaf.name,
    ));
    out.push_str(&format!("type {} struct {{\n", struct_name));
    for field in leaf.user_fields() {
        out.push_str(&format!(
            "\t{} {} // {} ({})\n",
            to_pascal_case(&field.name),
            go_type_for_field(field),
            field.ark_type,
            field.encoding.as_str(),
        ));
    }
    for field in leaf.witness_fields.iter().filter(|f| f.is_injected) {
        out.push_str(&format!(
            "\t// {} injected by Arkade\n",
            to_pascal_case(&field.name)
        ));
    }
    out.push_str("}\n\n");
}

/// Pick a Go receiver name that won't collide with 'w' (the witness parameter name).
fn pick_receiver(contract_name: &str) -> String {
    let first = contract_name
        .chars()
        .next()
        .unwrap_or('c')
        .to_ascii_lowercase();
    if first == 'w' {
        "ct".to_string()
    } else {
        first.to_string()
    }
}

fn emit_go_method(
    out: &mut String,
    ir: &ContractIR,
    group: &GroupIR,
    leaf: &LeafIR,
    receiver: &str,
) {
    let method_name = leaf_suffix(group, leaf);
    let witness_type = witness_struct_name(ir, group, leaf);

    out.push_str(&format!(
        "// {} spends the {} leaf of the {} group.\n",
        method_name, leaf.name, group.name,
    ));
    out.push_str(&format!(
        "func ({} *{}) {}(w {}) (*ark.WitnessStack, error) {{\n",
        receiver, ir.name, method_name, witness_type,
    ));
    out.push_str(&format!(
        "\treturn {}.BuildWitness(\"{}\", \"{}\", []ark.WitnessField{{\n",
        receiver, group.name, leaf.name,
    ));
    for field in leaf.user_fields() {
        out.push_str(&format!(
            "\t\t{{Name: \"{}\", Value: {}, Encoding: {}}},\n",
            field.name,
            value_expr(field, "w"),
            encoding_const(&field.encoding),
        ));
    }
    out.push_str("\t})\n}\n\n");
}

/// Escape a string for use in a Go interpreted string literal ("...").
fn escape_go_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 16);
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out
}
