use crate::ir::{ContractIR, Encoding, Field, FunctionIR};
use crate::naming::{to_camel_case, to_pascal_case, to_snake_case};
use crate::targets::{CodegenOptions, CodegenTarget, GeneratedFile};

pub struct GoTarget;

impl CodegenTarget for GoTarget {
    fn name(&self) -> &str {
        "go"
    }

    fn file_extension(&self) -> &str {
        "go"
    }

    fn generate(&self, ir: &ContractIR, options: &CodegenOptions) -> Result<GeneratedFile, String> {
        let filename = format!("{}.go", to_snake_case(&ir.name));
        let content = generate_go(ir, options);
        Ok(GeneratedFile { filename, content })
    }
}

fn go_type(encoding: &Encoding) -> &'static str {
    match encoding {
        Encoding::Compressed33 => "[33]byte",
        Encoding::Schnorr64 => "[64]byte",
        Encoding::Raw => "[]byte",
        Encoding::Raw20 => "[20]byte",
        Encoding::Raw32 => "[32]byte",
        Encoding::ScriptNum => "int64",
        Encoding::Le64 => "uint64",
        Encoding::Le32 => "uint32",
        Encoding::Unknown(_) => "[]byte",
    }
}

/// Whether this encoding uses a fixed-size array (needs [:] for slice conversion).
fn is_fixed_array(encoding: &Encoding) -> bool {
    matches!(
        encoding,
        Encoding::Compressed33 | Encoding::Schnorr64 | Encoding::Raw20 | Encoding::Raw32
    )
}

/// Map encoding to the ark SDK constant name.
fn encoding_const(encoding: &Encoding) -> &'static str {
    match encoding {
        Encoding::Compressed33 => "ark.Compressed33",
        Encoding::Schnorr64 => "ark.Schnorr64",
        Encoding::Raw => "ark.Raw",
        Encoding::Raw20 => "ark.Raw20",
        Encoding::Raw32 => "ark.Raw32",
        Encoding::ScriptNum => "ark.ScriptNum",
        Encoding::Le64 => "ark.Le64",
        Encoding::Le32 => "ark.Le32",
        Encoding::Unknown(_) => "ark.Raw",
    }
}

/// How to convert a Go typed field value to []byte for the witness builder.
fn value_expr(field: &Field, prefix: &str) -> String {
    let go_name = to_pascal_case(&field.name);
    match field.encoding {
        Encoding::ScriptNum => {
            format!("ark.EncodeScriptNum({}.{})", prefix, go_name)
        }
        Encoding::Le64 => {
            format!("ark.EncodeLe64({}.{})", prefix, go_name)
        }
        Encoding::Le32 => {
            format!("ark.EncodeLe32({}.{})", prefix, go_name)
        }
        _ if is_fixed_array(&field.encoding) => {
            format!("{}.{}[:]", prefix, go_name)
        }
        _ => {
            format!("{}.{}", prefix, go_name)
        }
    }
}

fn generate_go(ir: &ContractIR, options: &CodegenOptions) -> String {
    let mut out = String::new();

    let version = ir.compiler_version.as_deref().unwrap_or("unknown");
    let package = options.package_name.as_deref().unwrap_or("contracts");

    // Header
    let embed_import = if options.embed_artifact {
        ""
    } else {
        "\n\t_ \"embed\""
    };
    out.push_str(&format!(
        "// Code generated by arkade-bindgen v0.1.0. DO NOT EDIT.\n\
         // Source contract: {}\n\
         // Compiler: arkade-compiler v{}\n\n\
         package {}\n\n\
         import ({embed}\n\t\"github.com/arkade-os/contract-sdk-go/ark\"\n)\n\n",
        ir.name,
        version,
        package,
        embed = embed_import,
    ));

    // Constructor params struct
    out.push_str(&format!(
        "// {}Params holds constructor parameters for the {} contract.\n",
        ir.name, ir.name
    ));
    out.push_str(&format!("type {}Params struct {{\n", ir.name));
    for field in &ir.constructor_fields {
        let go_name = to_pascal_case(&field.name);
        out.push_str(&format!(
            "\t{} {} // {} ({})\n",
            go_name,
            go_type(&field.encoding),
            field.ark_type,
            field.encoding.as_str(),
        ));
    }
    out.push_str("}\n\n");

    // Per-function witness structs
    for func in &ir.functions {
        emit_witness_struct(&mut out, ir, func, &func.cooperative, "Cooperative");
        emit_witness_struct(&mut out, ir, func, &func.exit, "Exit");
    }

    // Contract struct
    out.push_str(&format!("// {} wraps an Ark contract instance.\n", ir.name));
    out.push_str(&format!(
        "type {} struct {{\n\t*ark.Contract\n}}\n\n",
        ir.name
    ));

    // Constructor function
    let camel_name = to_camel_case(&ir.name);
    out.push_str(&format!(
        "// New{} creates a new {} contract instance.\n",
        ir.name, ir.name
    ));
    out.push_str(&format!(
        "func New{}(params {}Params) (*{}, error) {{\n",
        ir.name, ir.name, ir.name,
    ));
    out.push_str(&format!(
        "\tc, err := ark.NewContract({}Artifact, ark.ConstructorArgs{{\n",
        camel_name,
    ));
    for field in &ir.constructor_fields {
        out.push_str(&format!(
            "\t\t{{Name: \"{}\", Value: {}, Encoding: {}}},\n",
            field.name,
            value_expr(field, "params"),
            encoding_const(&field.encoding),
        ));
    }
    out.push_str("\t})\n");
    out.push_str("\tif err != nil {\n\t\treturn nil, err\n\t}\n");
    out.push_str(&format!(
        "\treturn &{}{{Contract: c}}, nil\n}}\n\n",
        ir.name
    ));

    // Function methods — pick a receiver name that doesn't collide with 'w' (witness param)
    let receiver = pick_receiver(&ir.name);
    for func in &ir.functions {
        emit_go_method(
            &mut out,
            ir,
            func,
            &func.cooperative,
            "Cooperative",
            &receiver,
        );
        emit_go_method(&mut out, ir, func, &func.exit, "Exit", &receiver);
    }

    // Artifact constant
    if options.embed_artifact {
        if let Some(ref json) = options.artifact_json {
            out.push_str(&format!(
                "var {}Artifact = []byte(`{}`)\n",
                camel_name,
                json.trim(),
            ));
        }
    } else {
        let snake_name = to_snake_case(&ir.name);
        out.push_str(&format!(
            "//go:embed {}.json\nvar {}Artifact []byte\n",
            snake_name, camel_name,
        ));
    }

    out
}

fn emit_witness_struct(
    out: &mut String,
    ir: &ContractIR,
    func: &FunctionIR,
    variant: &crate::ir::VariantIR,
    variant_label: &str,
) {
    let pascal_func = to_pascal_case(&func.name);
    let struct_name = format!("{}{}{}Witness", ir.name, pascal_func, variant_label);

    let path_label = if variant_label == "Cooperative" {
        "cooperative path"
    } else {
        "exit path"
    };
    out.push_str(&format!(
        "// {} holds witness data for {}.{} ({}).\n",
        struct_name, ir.name, func.name, path_label,
    ));

    out.push_str(&format!("type {} struct {{\n", struct_name));
    for field in &variant.user_fields {
        let go_name = to_pascal_case(&field.name);
        out.push_str(&format!(
            "\t{} {} // {} ({})\n",
            go_name,
            go_type(&field.encoding),
            field.ark_type,
            field.encoding.as_str(),
        ));
    }

    if variant_label == "Cooperative" {
        out.push_str("\t// ServerSig injected by Ark server\n");
    } else if variant.is_nofn_fallback {
        out.push_str("\t// N-of-N multisig exit fallback\n");
    } else {
        out.push_str("\t// Exit timelock enforced by script\n");
    }
    out.push_str("}\n\n");
}

/// Pick a Go receiver name that won't collide with 'w' (the witness parameter name).
fn pick_receiver(contract_name: &str) -> String {
    let first = contract_name
        .chars()
        .next()
        .unwrap_or('c')
        .to_ascii_lowercase();
    if first == 'w' {
        // Use 'ct' to avoid collision with witness param 'w'
        "ct".to_string()
    } else {
        first.to_string()
    }
}

fn emit_go_method(
    out: &mut String,
    ir: &ContractIR,
    func: &FunctionIR,
    variant: &crate::ir::VariantIR,
    variant_label: &str,
    receiver: &str,
) {
    let pascal_func = to_pascal_case(&func.name);
    let method_name = format!("{}{}", pascal_func, variant_label);
    let witness_type = format!("{}{}{}Witness", ir.name, pascal_func, variant_label);
    let server_variant = variant_label == "Cooperative";

    out.push_str(&format!(
        "// {} executes the {} path of {}.\n",
        method_name,
        variant_label.to_lowercase(),
        func.name,
    ));
    out.push_str(&format!(
        "func ({} *{}) {}(w {}) (*ark.WitnessStack, error) {{\n",
        receiver, ir.name, method_name, witness_type,
    ));
    out.push_str(&format!(
        "\treturn {}.BuildWitness(\"{}\", {}, []ark.WitnessField{{\n",
        receiver, func.name, server_variant,
    ));

    for field in &variant.user_fields {
        out.push_str(&format!(
            "\t\t{{Name: \"{}\", Value: {}, Encoding: {}}},\n",
            field.name,
            value_expr(field, "w"),
            encoding_const(&field.encoding),
        ));
    }

    out.push_str("\t})\n}\n\n");
}
