use crate::ir::{ContractIR, Encoding, Field, FunctionIR, VariantIR};
use crate::naming::{to_camel_case, to_snake_case};
use crate::targets::{CodegenOptions, CodegenTarget, GeneratedFile};

pub struct TypeScriptTarget;

impl CodegenTarget for TypeScriptTarget {
    fn name(&self) -> &str {
        "typescript"
    }

    fn file_extension(&self) -> &str {
        "ts"
    }

    fn generate(&self, ir: &ContractIR, options: &CodegenOptions) -> Result<GeneratedFile, String> {
        let filename = format!("{}.ts", to_snake_case(&ir.name));
        let content = generate_typescript(ir, options);
        Ok(GeneratedFile { filename, content })
    }
}

fn ts_type(encoding: &Encoding) -> &'static str {
    match encoding {
        Encoding::Compressed33
        | Encoding::Schnorr64
        | Encoding::Raw
        | Encoding::Raw20
        | Encoding::Raw32 => "Uint8Array",
        Encoding::ScriptNum | Encoding::Le64 => "bigint",
        Encoding::Le32 => "number",
        Encoding::Unknown(_) => "Uint8Array",
    }
}

/// Map encoding to runtime SDK type alias name for imports.
fn sdk_type_alias(encoding: &Encoding) -> Option<&'static str> {
    match encoding {
        Encoding::Compressed33 => Some("Pubkey"),
        Encoding::Schnorr64 => Some("Signature"),
        Encoding::Raw => Some("Bytes"),
        Encoding::Raw20 => Some("Bytes20"),
        Encoding::Raw32 => Some("Bytes32"),
        _ => None,
    }
}

fn generate_typescript(ir: &ContractIR, options: &CodegenOptions) -> String {
    let mut out = String::new();

    // File header
    let version = ir.compiler_version.as_deref().unwrap_or("unknown");
    out.push_str(&format!(
        "// Auto-generated by arkade-bindgen v0.1.0\n\
         // Source contract: {}\n\
         // Compiler: arkade-compiler v{}\n\
         // Do not edit manually.\n\n",
        ir.name, version,
    ));

    // Collect needed SDK type aliases from all fields
    let mut type_aliases = std::collections::BTreeSet::new();
    for field in &ir.constructor_fields {
        if let Some(alias) = sdk_type_alias(&field.encoding) {
            type_aliases.insert(alias);
        }
    }
    for func in &ir.functions {
        for field in &func.cooperative.user_fields {
            if let Some(alias) = sdk_type_alias(&field.encoding) {
                type_aliases.insert(alias);
            }
        }
        for field in &func.exit.user_fields {
            if let Some(alias) = sdk_type_alias(&field.encoding) {
                type_aliases.insert(alias);
            }
        }
    }

    // Imports
    let mut imports: Vec<&str> = vec!["ArkContract"];
    for alias in &type_aliases {
        imports.push(alias);
    }
    out.push_str(&format!(
        "import {{ {} }} from \"@arkade-os/contract-sdk\";\n",
        imports
            .iter()
            .enumerate()
            .map(|(i, s)| {
                if i == 0 {
                    s.to_string()
                } else {
                    format!("type {}", s)
                }
            })
            .collect::<Vec<_>>()
            .join(", ")
    ));

    // Artifact import/embed
    let snake_name = to_snake_case(&ir.name);
    if options.embed_artifact {
        if let Some(ref json) = options.artifact_json {
            out.push_str(&format!("\nconst artifact = {} as const;\n", json.trim()));
        }
    } else {
        out.push_str(&format!(
            "import artifact from \"./{}.json\";\n",
            snake_name
        ));
    }
    out.push('\n');

    // Constructor params interface
    out.push_str(&format!("/** Constructor parameters for {} */\n", ir.name));
    out.push_str(&format!("export interface {}Params {{\n", ir.name));
    for field in &ir.constructor_fields {
        let ts = field_ts_type(field);
        out.push_str(&format!(
            "  /** {} ({}) */\n  {}: {};\n",
            field.ark_type,
            field.encoding.as_str(),
            to_camel_case(&field.name),
            ts,
        ));
    }
    out.push_str("}\n\n");

    // Per-function witness interfaces
    for func in &ir.functions {
        emit_witness_interface(&mut out, ir, func, &func.cooperative, "Cooperative");
        emit_witness_interface(&mut out, ir, func, &func.exit, "Exit");
    }

    // Contract class
    out.push_str(&format!(
        "export class {} extends ArkContract<{}Params> {{\n",
        ir.name, ir.name,
    ));
    out.push_str("  static readonly artifact = artifact;\n\n");
    out.push_str(&format!(
        "  constructor(params: {}Params) {{\n\
         \x20   super({}.artifact, params);\n\
         \x20 }}\n",
        ir.name, ir.name,
    ));

    // Function methods
    for func in &ir.functions {
        let method_name = to_camel_case(&func.name);
        let pascal_name = crate::naming::to_pascal_case(&func.name);

        let coop_type = format!("{}{}CooperativeWitness", ir.name, pascal_name);
        let exit_type = format!("{}{}ExitWitness", ir.name, pascal_name);

        out.push_str(&format!(
            "\n\
             \x20 {} = {{\n\
             \x20   cooperative: (witness: {}) =>\n\
             \x20     this.buildWitness(\"{}\", true, witness),\n\
             \x20   exit: (witness: {}) =>\n\
             \x20     this.buildWitness(\"{}\", false, witness),\n\
             \x20 }};\n",
            method_name, coop_type, func.name, exit_type, func.name,
        ));
    }

    out.push_str("}\n");
    out
}

fn emit_witness_interface(
    out: &mut String,
    ir: &ContractIR,
    func: &FunctionIR,
    variant: &VariantIR,
    variant_label: &str,
) {
    let pascal_name = crate::naming::to_pascal_case(&func.name);
    let iface_name = format!("{}{}{}Witness", ir.name, pascal_name, variant_label);

    // Doc comment
    let path_label = if variant_label == "Cooperative" {
        "cooperative path"
    } else {
        "exit path"
    };
    out.push_str(&format!(
        "/** Witness for {}.{} ({}) */\n",
        ir.name, func.name, path_label,
    ));

    out.push_str(&format!("export interface {} {{\n", iface_name));

    for field in &variant.user_fields {
        let ts = field_ts_type(field);
        out.push_str(&format!(
            "  /** {} ({}) */\n  {}: {};\n",
            field.ark_type,
            field.encoding.as_str(),
            to_camel_case(&field.name),
            ts,
        ));
    }

    // Comments for server-injected or timelock fields
    if variant_label == "Cooperative" {
        out.push_str("  // serverSig injected by Ark server\n");
    } else if variant.is_nofn_fallback {
        out.push_str("  // N-of-N multisig exit fallback\n");
    } else {
        out.push_str("  // exit timelock enforced by script\n");
    }

    out.push_str("}\n\n");
}

/// Get the TypeScript type for a field, preferring SDK aliases.
/// Distinguishes `bool` (→ `boolean`) from `int` (→ `bigint`) even though
/// both use `ScriptNum` encoding on the wire.
fn field_ts_type(field: &Field) -> &'static str {
    if field.ark_type == "bool" {
        return "boolean";
    }
    if let Some(alias) = sdk_type_alias(&field.encoding) {
        alias
    } else {
        ts_type(&field.encoding)
    }
}
