use crate::ir::{ContractIR, Encoding, Field, GroupIR, LeafIR};
use crate::naming::{to_camel_case, to_pascal_case, to_snake_case};
use crate::targets::{CodegenOptions, CodegenTarget, GeneratedFile};

pub struct TypeScriptTarget;

impl CodegenTarget for TypeScriptTarget {
    fn name(&self) -> &str {
        "typescript"
    }

    fn file_extension(&self) -> &str {
        "ts"
    }

    fn generate(&self, ir: &ContractIR, options: &CodegenOptions) -> Result<GeneratedFile, String> {
        let filename = format!("{}.ts", to_snake_case(&ir.name));
        let content = generate_typescript(ir, options);
        Ok(GeneratedFile { filename, content })
    }
}

fn ts_type(encoding: &Encoding) -> &'static str {
    match encoding {
        Encoding::Compressed33
        | Encoding::Schnorr64
        | Encoding::Raw
        | Encoding::Raw20
        | Encoding::Raw32 => "Uint8Array",
        Encoding::ScriptNum => "bigint",
        Encoding::Unknown(_) => "Uint8Array",
    }
}

/// Map encoding to runtime SDK type alias name for imports.
fn sdk_type_alias(encoding: &Encoding) -> Option<&'static str> {
    match encoding {
        Encoding::Compressed33 => Some("Pubkey"),
        Encoding::Schnorr64 => Some("Signature"),
        Encoding::Raw => Some("Bytes"),
        Encoding::Raw20 => Some("Bytes20"),
        Encoding::Raw32 => Some("Bytes32"),
        _ => None,
    }
}

fn field_name(name: &str) -> String {
    // Flat dotted paths stay verbatim so they cannot collide with underscored names.
    if name.contains('.') {
        format!("\"{name}\"")
    } else {
        to_camel_case(name)
    }
}

/// Witness interface name for a leaf. Collapses the redundant name when a group
/// has a single leaf sharing its name (e.g. `HTLCClaimWitness`, not
/// `HTLCClaimClaimWitness`).
fn witness_iface_name(ir: &ContractIR, group: &GroupIR, leaf: &LeafIR) -> String {
    if leaf.name == group.name {
        format!("{}{}Witness", ir.name, to_pascal_case(&group.name))
    } else {
        format!(
            "{}{}{}Witness",
            ir.name,
            to_pascal_case(&group.name),
            to_pascal_case(&leaf.name)
        )
    }
}

fn generate_typescript(ir: &ContractIR, options: &CodegenOptions) -> String {
    let mut out = String::new();

    // File header
    let version = ir.compiler_version.as_deref().unwrap_or("unknown");
    out.push_str(&format!(
        "// Auto-generated by arkade-bindgen v0.1.0\n\
         // Source contract: {}\n\
         // Compiler: arkade-compiler v{}\n\
         // Do not edit manually.\n\n",
        ir.name, version,
    ));

    // Collect needed SDK type aliases from all user-supplied fields.
    let mut type_aliases = std::collections::BTreeSet::new();
    for field in &ir.constructor_fields {
        if let Some(alias) = sdk_type_alias(&field.encoding) {
            type_aliases.insert(alias);
        }
    }
    for group in &ir.groups {
        for leaf in &group.leaves {
            for field in leaf.user_fields() {
                if let Some(alias) = sdk_type_alias(&field.encoding) {
                    type_aliases.insert(alias);
                }
            }
        }
    }

    // Imports
    let mut imports: Vec<&str> = vec!["ArkContract"];
    for alias in &type_aliases {
        imports.push(alias);
    }
    out.push_str(&format!(
        "import {{ {} }} from \"@arkade-os/contract-sdk\";\n",
        imports
            .iter()
            .enumerate()
            .map(|(i, s)| {
                if i == 0 {
                    s.to_string()
                } else {
                    format!("type {}", s)
                }
            })
            .collect::<Vec<_>>()
            .join(", ")
    ));

    // Artifact import/embed
    let snake_name = to_snake_case(&ir.name);
    if options.embed_artifact {
        if let Some(ref json) = options.artifact_json {
            out.push_str(&format!("\nconst artifact = {} as const;\n", json.trim()));
        }
    } else {
        out.push_str(&format!(
            "import artifact from \"./{}.json\";\n",
            snake_name
        ));
    }
    out.push('\n');

    // Constructor params interface
    out.push_str(&format!("/** Constructor parameters for {} */\n", ir.name));
    out.push_str(&format!("export interface {}Params {{\n", ir.name));
    for field in &ir.constructor_fields {
        out.push_str(&format!(
            "  /** {} ({}) */\n  {}: {};\n",
            field.ark_type,
            field.encoding.as_str(),
            field_name(&field.name),
            field_ts_type(field),
        ));
    }
    out.push_str("}\n\n");

    // Per-leaf witness interfaces
    for group in &ir.groups {
        for leaf in &group.leaves {
            emit_witness_interface(&mut out, ir, group, leaf);
        }
    }

    // Contract class
    out.push_str(&format!(
        "export class {} extends ArkContract<{}Params> {{\n",
        ir.name, ir.name,
    ));
    out.push_str("  static readonly artifact = artifact;\n\n");
    out.push_str(&format!(
        "  constructor(params: {}Params) {{\n\
         \x20   super({}.artifact, params);\n\
         \x20 }}\n",
        ir.name, ir.name,
    ));

    // Per-group spend methods: an object keyed by leaf name.
    for group in &ir.groups {
        let method_name = to_camel_case(&group.name);
        out.push_str(&format!("\n  {} = {{\n", method_name));
        for leaf in &group.leaves {
            let iface = witness_iface_name(ir, group, leaf);
            out.push_str(&format!(
                "    {}: (witness: {}) =>\n\
                 \x20     this.buildWitness(\"{}\", \"{}\", witness),\n",
                to_camel_case(&leaf.name),
                iface,
                group.name,
                leaf.name,
            ));
        }
        out.push_str("  };\n");
    }

    out.push_str("}\n");
    out
}

fn emit_witness_interface(out: &mut String, ir: &ContractIR, group: &GroupIR, leaf: &LeafIR) {
    let iface_name = witness_iface_name(ir, group, leaf);

    out.push_str(&format!(
        "/** Witness for {}.{} (leaf: {}) */\n",
        ir.name, group.name, leaf.name,
    ));
    out.push_str(&format!("export interface {} {{\n", iface_name));

    for field in leaf.user_fields() {
        out.push_str(&format!(
            "  /** {} ({}) */\n  {}: {};\n",
            field.ark_type,
            field.encoding.as_str(),
            field_name(&field.name),
            field_ts_type(field),
        ));
    }

    // Note infrastructure-injected witness fields the caller does not supply.
    for field in leaf.witness_fields.iter().filter(|f| f.is_injected) {
        out.push_str(&format!("  // {} injected by Arkade\n", field.name));
    }

    out.push_str("}\n\n");
}

/// Get the TypeScript type for a field, preferring SDK aliases.
/// Distinguishes `bool` (→ `boolean`) from `int` (→ `bigint`) even though
/// both use `ScriptNum` encoding on the wire.
fn field_ts_type(field: &Field) -> &'static str {
    if field.ark_type == "bool" {
        return "boolean";
    }
    if let Some(alias) = sdk_type_alias(&field.encoding) {
        alias
    } else {
        ts_type(&field.encoding)
    }
}
